name: CI and CD For Vote 
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Building, Pushing and Deploying the Image for vote
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: File changes for vote  
      id: vote
      uses: tj-actions/changed-files@v34
      with:
        files: |
            /example-voting-app/vote/**
     
    -  name: Build and push customer image
       if: steps.vote.outputs.any_changed == 'true'
       env:
         image-name-vote: vote
         
       id: build-and-push-vote-image
       uses: docker/build-push-action@v3
       with:
        context: ./example-voting-app/vote
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.image-name-vote }}:${{ github.sha }}
        
      
